export const getData: IGetData = {
  categoryTypes: [
    {
      id: 1,
      label: "Sport",
      value: "sport",
      count: 10,
    },
    {
      id: 2,
      label: "SUV",
      value: "suv",
      count: 12,
    },
    {
      id: 3,
      label: "MPV",
      value: "mpv",
      count: 16,
    },
    {
      id: 4,
      label: "Sedan",
      value: "sedan",
      count: 20,
    },
    {
      id: 5,
      label: "Coupe",
      value: "coupe",
      count: 14,
    },
    {
      id: 6,
      label: "Hatchback",
      value: "hatchback",
      count: 14,
    },
  ],
  carCapacityOptions: [
    {
      id: 1,
      label: "2 Person",
      value: "2_person",
      count: 10,
    },
    {
      id: 2,
      label: "4 Person",
      value: "4_person",
      count: 14,
    },
    {
      id: 3,
      label: "6 Person",
      value: "6_person",
      count: 12,
    },
    {
      id: 4,
      label: "8 or More",
      value: "8_or_more",
      count: 16,
    },
  ],
};

export const dashboardData: IDashboardData = {
  slots: [
    {
      id: "44bb5a87-8e1b-4acd-8f1c-55d6a0b94626",
      title: "The Best Platform for Car Rental",
      content:
        "Ease of doing a car rental safely and reliably. Of course at a low price.",
      image_url: "/temp/koenigsegg.png",
      flip: false,
    },
    {
      id: "c3e656a0-239c-46a1-ab15-c13ce5e191e3",
      title: "Easy way to rent a car at a low price",
      content:
        "Providing cheap car rental services and safe and comfortable facilities.",
      image_url: "/temp/nissan_gt_r.png",
      flip: true,
    },
  ],
  locationOptions: [
    { value: "new-york", label: "New York" },
    { value: "los-angeles", label: "Los Angeles" },
    { value: "chicago", label: "Chicago" },
    { value: "houston", label: "Houston" },
    { value: "miami", label: "Miami" },
    { value: "semarang", label: "Semarang" },
  ],
  popular_car: [
    {
      id: "895aa651-0bf7-40f1-8f93-a11c7309dd9b",
      title: "Koenigsegg",
      category: "Sport",
      user_liked: true,
      image_url: "/temp/koenigsegg.png",
      fuelCapacity: "90L",
      transmission: "Manual",
      seats: 2,
      price: 99,
      flip: false,
    },
    {
      id: "f6b2b828-a5c8-4925-8a7a-065aff9535c6",
      title: "Nissan GT - R",
      category: "Sport",
      user_liked: false,
      image_url: "/temp/nissan_gt_r.png",
      fuelCapacity: "80L",
      transmission: "Manual",
      seats: 2,
      price: 80,
      originalPrice: 100,
      flip: true,
      views: [
        "/images/f6b2b828-a5c8-4925-8a7a-065aff9535c6-view-1.png",
        "/images/f6b2b828-a5c8-4925-8a7a-065aff9535c6-view-2.png",
        "/images/f6b2b828-a5c8-4925-8a7a-065aff9535c6-view-3.png",
      ],
    },
    {
      id: "4fb75ad7-aa65-4566-80d9-e6a0d47005b7",
      title: "Rolls - Royce",
      category: "Sedan",
      user_liked: true,
      image_url: "/temp/rolls_royce.png",
      fuelCapacity: "70L",
      transmission: "Manual",
      seats: 4,
      price: 96,
      flip: true,
    },
    {
      id: "3c243a4f-39f9-4df1-9ad5-777a6d131239",
      title: "Nissan GT - R",
      category: "Sport",
      user_liked: false,
      image_url: "/temp/nissan_gt_r.png",
      fuelCapacity: "80L",
      transmission: "Manual",
      seats: 2,
      price: 80,
      originalPrice: 100,
      flip: true,
    },
  ],
  recomendation_car: [
    {
      id: "560dca99-ebe9-44d3-b16f-7e1e570ecfb5",
      title: "All New Rush",
      category: "SUV",
      user_liked: false,
      image_url: "/temp/all_new_rush.png",
      fuelCapacity: "70L",
      transmission: "Manual",
      seats: 6,
      price: 72,
      originalPrice: 80,
      flip: false,
    },
    {
      id: "ca3e45a2-9929-4f8c-8bb4-c3454b18cca3",
      title: "CR - V",
      category: "SUV",
      user_liked: true,
      image_url: "/temp/cr_v.png",
      fuelCapacity: "80L",
      transmission: "Manual",
      seats: 6,
      price: 80,
      flip: true,
    },
    {
      id: "ba59139d-2a6e-461b-9b78-c6c4e08bef67",
      title: "All New Terios",
      category: "SUV",
      user_liked: false,
      image_url: "/temp/all_new_terios.png",
      fuelCapacity: "90L",
      transmission: "Manual",
      seats: 6,
      price: 74,
      flip: false,
    },
    {
      id: "7be4a7f6-81ef-4b59-acc3-df244c86a78d",
      title: "CR - V",
      category: "SUV",
      user_liked: true,
      image_url: "/temp/cr_v.png",
      fuelCapacity: "80L",
      transmission: "Manual",
      seats: 6,
      price: 80,
      flip: true,
    },
    {
      id: "fc7f8227-7ed4-459a-a08e-58ddc227a837",
      title: "MG ZX Exclusice",
      category: "Hatchback",
      user_liked: true,
      image_url: "/temp/mg_zx_exclusice.png",
      fuelCapacity: "70L",
      transmission: "Manual",
      seats: 4,
      price: 76,
      originalPrice: 80,
      flip: false,
    },
    {
      id: "695ed4a9-9e40-4169-9a9e-7c46512e7506",
      title: "New MG ZS",
      category: "SUV",
      user_liked: false,
      image_url: "/temp/new_mg_zs.png",
      fuelCapacity: "80L",
      transmission: "Manual",
      seats: 6,
      price: 80,
      flip: true,
    },
    {
      id: "e08ace19-c796-4ae8-bfed-b71cc873533b",
      title: "MG ZX Excite",
      category: "Hatchback",
      user_liked: true,
      image_url: "/temp/mg_zx_excite.png",
      fuelCapacity: "90L",
      transmission: "Manual",
      seats: 4,
      price: 74,
      flip: false,
    },
    {
      id: "4ed741ea-3ac6-4176-8754-58d63dc012db",
      title: "New MG ZS",
      category: "SUV",
      user_liked: false,
      image_url: "/temp/new_mg_zs.png",
      fuelCapacity: "80L",
      transmission: "Manual",
      seats: 6,
      price: 80,
      flip: true,
    },
  ],
  pickup: {
    location: "semarang",
    date: "20-07-2022",
    time: "07:00 AM",
  },
  dropoff: {
    location: "semarang",
    date: "21-07-2022",
    time: "01:00 AM",
  },
};
